services:
  webtop:
    image: lscr.io/linuxserver/webtop:fedora-mate
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /Users/nicolasfuentes/LinuxWebTop_Docker-:/config
    ports:
      - "3000:3000"
      - "3001:3001"
    shm_size: "2gb"
    restart: unless-stopped
